### ISSUE TITLE
Add support for Gradle version catalog in with_cache command

### ISSUE THREAD

**Issue by canatella** [CircleCI-Public/gradle-orb#21]
**Is your feature request related to a problem? Please describe.**
Gradle now has a standard way of sharing dependencies across projects: https://docs.gradle.org/current/userguide/platforms.html using `settings.gradle`, `settings.gradle.kts` and/or `gradle/libs.versions.toml`. Currently, there is no way to tell the orb to add those file to the cache key checksum.

**Describe the solution you'd like**
The cache key checksum generation could be updated to add those files to the checksum:
```
command: |
  find . -name "${PARAM_CHECKSUM_FILES}" -or -name "settings.gradle" -or -name "settings.gradle.kts" -or -name "libs.versions.toml" | sort | xargs cat | shasum | awk 
```
**Describe alternatives you've considered**
I'm currently updating the `cache_key` parameter manually when updating those files but I'm pretty sure I'll forget at some point.

**Comment by ryanbourdais** [comment]
Hi @canatella are you looking to cache multiple files, or just have different options? Currently, I believe changing the `deps_checksum_file` or `wrapper_checksum_file` param when calling `with_cache` will cache the files you specify. If you are looking to cache multiple files in the same command that is currently not supported but I can begin looking into that.

**Comment by canatella** [comment]
I need to use multiple files with different names for the seed, this is what I'm using at the moment instead of the orb:
```yaml
       - run:
           command: |
             find . -name build.gradle.kts -or -name settings.gradle.kts -or -name libs.versions.toml | sort | xargs cat | shasum | awk '{print $1}' > "${CHECKSUM_SEED_LOCATION}"
           environment:
             CHECKSUM_SEED_LOCATION: /tmp/gradle_dep_cache_seed
             PARAM_CHECKSUM_FILES: << parameters.deps_checksum_file>>
           name: Generate Dependencies Checksum
```
