### ISSUE TITLE
Gradle/test store_artifacts unexpected argument

### ISSUE THREAD

**Issue by jpzabriskie** [CircleCI-Public/gradle-orb#7]
**Orb Version**
2.1.0

**Describe the bug**
Running the example provided to include custom test results:

workflows:
  build-and-publish:
    jobs:
      - gradle/test:
          store_artifacts: build/reports/
          test_command: myTests
          test_results_path: build/test-results/

Returned the following error:

Error calling workflow: 'build-and-publish'
Error calling job: 'gradle/test'
Unexpected argument(s): store_artifacts

**To Reproduce**
Copy and past provide example from orb registry into circle Config and run build

**Expected behavior**

The specific bit I'm after here is the store_artifacts command, I'd like to use this to store a jar. I attempted this example build to try to understand how the functionality works within the orb but it appears to be broken or incorrectly documented.

**Additional context**

N/A

**Comment by gmemstr** [comment]
@jpzabriskie The `store_artifacts` parameter is not a valid argument for the `gradle/test` command - I believe our `post-steps` and `pre-steps` may help here, as documented here: https://circleci.com/docs/2.0/reusing-config/#defining-pre-and-post-steps.

**Comment by EricRibeiro** [comment]
Closed due to inactivity.

**Comment by khuongln-1346** [comment]
@jpzabriskie 

The document of gradle-orb is not correct

You can use this config:
```
workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          reports_path: build/reports/ ### =>>> reports_path, not store_artifacts
          test_results_path: build/test-results/
```

Refer: https://circleci.com/developer/orbs/orb/circleci/gradle#orb-source
